### ISSUE TITLE
cannot use vue-native init <project-name>

### ISSUE THREAD

**Issue by Wrufesh** [GeekyAnts/vue-native-cli#10]
I was following [this guide](https://vue-native.io/docs/installation.html).
I have installed **create-react-native-app** globally. 

When I put this following command:
`vue-native init family`

I get this following error:

```
Error In Getting Crna Package Version { Error: Command failed: expo --version 2>/dev/null
    at checkExecSyncError (child_process.js:622:11)
    at execSync (child_process.js:659:13)
    at Object.getCrnaVersionIfAvailable (/home/wrufesh/.config/yarn/global/node_modules/vue-native-cli/src/utils/validation.js:62:9)
    at Command.<anonymous> (/home/wrufesh/.config/yarn/global/node_modules/vue-native-cli/src/index.js:31:63)
    at Command.listener (/home/wrufesh/.config/yarn/global/node_modules/vue-native-cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:188:13)
    at Command.parseArgs (/home/wrufesh/.config/yarn/global/node_modules/vue-native-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/home/wrufesh/.config/yarn/global/node_modules/vue-native-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/wrufesh/.config/yarn/global/node_modules/vue-native-cli/src/index.js:70:9)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
  status: 127,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 12018,
  stdout: <Buffer >,
  stderr: <Buffer > }
Please globally install create-react-native-app dependency
```
What is the problem here. It would be great if someone would point me the mistake I am making here.

**Comment by rdeprey** [comment]
I had the same error. It seems like there's an Expo, https://expo.io/tools, dependency that's not mentioned in the tutorial. Try running npm install -g expo-cli. That resolved it for me.

**Comment by halben** [comment]
@rdeprey Thanks. 

Please update instruction to include step on install expo-cli globally. Thanks.

**Comment by neeraj-singh47** [comment]
The expo-cli requirement has been mentioned under the system requirements

**Comment by vahidalvandi** [comment]
i fixed it in ubunto with set permission in npm global

```

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH


npm install npm@latest -g
npm install node@latest -g


npm install react-native-cli -g
npm install expo-cli -g
npm install -g vue-native-cli
```

**Comment by yakupguvenc** [comment]
> i fixed it in ubunto with set permission in npm global
> 
> ```
> 
> sudo chown -R $USER:$GROUP ~/.npm
> sudo chown -R $USER:$GROUP ~/.config
> mkdir ~/.npm-global
> npm config set prefix '~/.npm-global'
> export PATH=~/.npm-global/bin:$PATH
> 
> 
> npm install npm@latest -g
> npm install node@latest -g
> 
> 
> npm install react-native-cli -g
> npm install expo-cli -g
> npm install -g vue-native-cli
> ```

thank you my friend
