### ISSUE TITLE
Error: Please globally install create-react-native-app dependency

### ISSUE THREAD

**Issue by ralyodio** [GeekyAnts/vue-native-cli#3]

**Comment by neeraj-singh47** [comment]
You need to install create-react-native-app globally using the command `npm install -g create-react-native-app`

**Comment by vijay-pratap** [comment]
In the Documentation Please mention there that installation for create-react-native-app dependency must be done with: npm install -g create-react-native-app

**Comment by TaenAhammed** [comment]
Though I installed create-react-native-app globally I till now have faced the problem.

**Comment by cristinaveale** [comment]
After `npm install -g create-react-native-app` I still get this error:
```
vue-native init vue-native-tester
Error In Getting Crna Package Version { Error: Command failed: expo --version 2>/dev/null
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.getCrnaVersionIfAvailable (/usr/local/lib/node_modules/vue-native-cli/src/utils/validation.js:62:9)
    at Command.<anonymous> (/usr/local/lib/node_modules/vue-native-cli/src/index.js:31:63)
    at Command.listener (/usr/local/lib/node_modules/vue-native-cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/vue-native-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/vue-native-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/vue-native-cli/src/index.js:70:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
  status: 127,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 52486,
  stdout: <Buffer >,
  stderr: <Buffer > }
Please globally install create-react-native-app dependency
```

**Comment by Adron** [comment]
Yup. Same on Ubuntu Linux. Budgie distro of that.

```
$ vue-native init projTest1
Error In Getting Crna Package Version { Error: Command failed: expo --version 2>/dev/null
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.getCrnaVersionIfAvailable (/home/adron/.nvm/versions/node/v10.15.3/lib/node_modules/vue-native-cli/src/utils/validation.js:62:9)
    at Command.<anonymous> (/home/adron/.nvm/versions/node/v10.15.3/lib/node_modules/vue-native-cli/src/index.js:31:63)
    at Command.listener (/home/adron/.nvm/versions/node/v10.15.3/lib/node_modules/vue-native-cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (/home/adron/.nvm/versions/node/v10.15.3/lib/node_modules/vue-native-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/home/adron/.nvm/versions/node/v10.15.3/lib/node_modules/vue-native-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/adron/.nvm/versions/node/v10.15.3/lib/node_modules/vue-native-cli/src/index.js:70:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
  status: 127,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 4916,
  stdout: <Buffer >,
  stderr: <Buffer > }
Please globally install create-react-native-app dependency
```

Version 2.0.2 is installed currently per issuing the `npm install -g create-react-native-app` command.

It seems like there is some missing React component that is required when getting started from scratch.

**Comment by jonbesga** [comment]
Same happening to me. I have installed the dependency and I'm still getting the error

Edit: Found the solution in https://github.com/GeekyAnts/vue-native-cli/issues/10#issuecomment-467974089

**Comment by guptaAvi22** [comment]
after using this command npm install -g create-react-native-app i get this error
npm WARN checkPermissions Missing write access to /usr/local/lib
/usr/local/lib
`-- create-react-native-app@2.0.2 
  +-- babel-runtime@6.26.0 
  | +-- core-js@2.6.9 
  | `-- regenerator-runtime@0.11.1 
  +-- chalk@2.4.2 
  | +-- ansi-styles@3.2.1 
  | | `-- color-convert@1.9.3 
  | |   `-- color-name@1.1.3 
  | +-- escape-string-regexp@1.0.5 
  | `-- supports-color@5.5.0 
  |   `-- has-flag@3.0.0 
  +-- cross-spawn@5.1.0 
  | +-- lru-cache@4.1.5 
  | | +-- pseudomap@1.0.2 
  | | `-- yallist@2.1.2 
  | +-- shebang-command@1.2.0 
  | | `-- shebang-regex@1.0.0 
  | `-- which@1.3.1 
  |   `-- isexe@2.0.0 
  +-- fs-extra@4.0.3 
  | +-- graceful-fs@4.1.15 
  | +-- jsonfile@4.0.0 
  | `-- universalify@0.1.2 
  +-- minimist@1.2.0 
  +-- path-exists@3.0.0 
  +-- semver@5.7.0 
  `-- source-map-support@0.4.18 
    `-- source-map@0.5.7 

npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "create-react-native-app"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/avinash/Documents/my_first_react_native_app/code/npm-debug.log

**Comment by jamalroger** [comment]
@guptaAvi22   just add sudo before the command


exp:sudo npm install ...........

**Comment by silvermiguel96** [comment]
Hello, do you have a solution? I already perform all the commands and it still does not work .

**Comment by ThickLine** [comment]
Something is missing. Did you install expo? npm install -g expo-cli

**Comment by vahidalvandi** [comment]
i fixed it in ubunto with set permission in npm global 
```

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH


npm install npm@latest -g
npm install node@latest -g


npm install react-native-cli -g
npm install expo-cli -g
npm install -g vue-native-cli
```
